import { Profile, InitiatorFeatures } from '../types';

export interface InitiatorProfile {
  id: string;
  name: string;
  age: number;
  photo: string;
  features: InitiatorFeatures;
}

export const INITIATORS: InitiatorProfile[] = [
  {
    id: 'u1',
    name: 'Sarah',
    age: 28,
    photo: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=600',
    features: {
      init_days_on_platform: 245,
      init_prior_conv_rate: 0.36,
      init_daily_swipes: 28,
      init_last_active_hours: 1.2,
      init_matches_24h: 6,
      init_subscription: true,
    },
  },
  {
    id: 'u2',
    name: 'Jessica',
    age: 26,
    photo: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600',
    features: {
      init_days_on_platform: 120,
      init_prior_conv_rate: 0.28,
      init_daily_swipes: 15,
      init_last_active_hours: 3.5,
      init_matches_24h: 4,
      init_subscription: false,
    },
  },
  {
    id: 'u3',
    name: 'Emma',
    age: 31,
    photo: 'https://images.pexels.com/photos/1181694/pexels-photo-1181694.jpeg?auto=compress&cs=tinysrgb&w=600',
    features: {
      init_days_on_platform: 450,
      init_prior_conv_rate: 0.52,
      init_daily_swipes: 42,
      init_last_active_hours: 0.5,
      init_matches_24h: 9,
      init_subscription: true,
    },
  },
  {
    id: 'u4',
    name: 'Amanda',
    age: 29,
    photo: 'https://images.pexels.com/photos/1270293/pexels-photo-1270293.jpeg?auto=compress&cs=tinysrgb&w=600',
    features: {
      init_days_on_platform: 180,
      init_prior_conv_rate: 0.18,
      init_daily_swipes: 12,
      init_last_active_hours: 8.0,
      init_matches_24h: 2,
      init_subscription: false,
    },
  },
  {
    id: 'u5',
    name: 'Rachel',
    age: 27,
    photo: 'https://images.pexels.com/photos/1181712/pexels-photo-1181712.jpeg?auto=compress&cs=tinysrgb&w=600',
    features: {
      init_days_on_platform: 320,
      init_prior_conv_rate: 0.44,
      init_daily_swipes: 35,
      init_last_active_hours: 2.0,
      init_matches_24h: 7,
      init_subscription: true,
    },
  },
];

const DEFAULT_INITIATOR: InitiatorFeatures = {
  init_days_on_platform: 245,
  init_prior_conv_rate: 0.36,
  init_daily_swipes: 28,
  init_last_active_hours: 1.2,
  init_matches_24h: 6,
  init_subscription: true,
};

export const RAW_PROFILES: Omit<Profile, 'engineered' | 'cil_score' | 'rank'>[] = [
  {
    id: 'p1',
    name: 'Lucas',
    age: 26,
    photo: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/1547971/pexels-photo-1547971.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Weekend hiker, dog dad & amateur chef. Always down for a good wine and great company.',
    interests: ['Outdoors', 'Food & Drink', 'Travel', 'Music'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.95,
      cand_last_active_hours: 0.8,
      cand_avg_response_time_h: 0.5,
      cand_photos: 5,
      cand_bio_length_words: 58,
      cand_reciprocal_like: true,
    },
    matchContext: {
      shared_interests_count: 5,
      distance_km: 2.8,
      match_age_hours: 1.5,
      time_of_day_evening: true,
    },
  },
  {
    id: 'p2',
    name: 'Alex',
    age: 28,
    photo: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Adventure lover • Dog dad • Beach enthusiast • Let\'s grab a drink!',
    interests: ['Travel', 'Sports', 'Music', 'Gaming'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.92,
      cand_last_active_hours: 1.0,
      cand_avg_response_time_h: 0.8,
      cand_photos: 5,
      cand_bio_length_words: 45,
      cand_reciprocal_like: true,
    },
    matchContext: {
      shared_interests_count: 4,
      distance_km: 3.2,
      match_age_hours: 2.0,
      time_of_day_evening: true,
    },
  },
  {
    id: 'p3',
    name: 'Marcus',
    age: 31,
    photo: 'https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Fitness coach by day, jazz musician by night. I make a killer pasta carbonara.',
    interests: ['Fitness', 'Music', 'Food & Drink', 'Art'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.88,
      cand_last_active_hours: 2.5,
      cand_avg_response_time_h: 1.2,
      cand_photos: 4,
      cand_bio_length_words: 52,
      cand_reciprocal_like: true,
    },
    matchContext: {
      shared_interests_count: 3,
      distance_km: 5.5,
      match_age_hours: 3.5,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p4',
    name: 'Ethan',
    age: 29,
    photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=300',
      'https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Software engineer who loves trail running and board games. Coffee is a personality trait.',
    interests: ['Gaming', 'Sports', 'Books', 'Travel'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.82,
      cand_last_active_hours: 3.0,
      cand_avg_response_time_h: 1.5,
      cand_photos: 4,
      cand_bio_length_words: 48,
      cand_reciprocal_like: true,
    },
    matchContext: {
      shared_interests_count: 3,
      distance_km: 6.8,
      match_age_hours: 5.0,
      time_of_day_evening: true,
    },
  },
  {
    id: 'p5',
    name: 'Jordan',
    age: 33,
    photo: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Marketing director. Obsessed with craft beer, vinyl records, and my Labrador.',
    interests: ['Music', 'Food & Drink', 'Outdoors'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.75,
      cand_last_active_hours: 6.0,
      cand_avg_response_time_h: 2.5,
      cand_photos: 3,
      cand_bio_length_words: 38,
      cand_reciprocal_like: true,
    },
    matchContext: {
      shared_interests_count: 2,
      distance_km: 9.2,
      match_age_hours: 8.0,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p6',
    name: 'Tyler',
    age: 27,
    photo: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [
      'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=300',
    ],
    bio: 'Architect + avid rock climber. Love farmers markets and exploring new neighbourhoods.',
    interests: ['Outdoors', 'Art', 'Travel'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.78,
      cand_last_active_hours: 8.0,
      cand_avg_response_time_h: 3.0,
      cand_photos: 3,
      cand_bio_length_words: 34,
      cand_reciprocal_like: false,
    },
    matchContext: {
      shared_interests_count: 2,
      distance_km: 12.5,
      match_age_hours: 10.0,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p7',
    name: 'Ryan',
    age: 30,
    photo: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [],
    bio: 'Just a chill guy who likes movies and long walks.',
    interests: ['Books', 'Food & Drink'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.62,
      cand_last_active_hours: 14.0,
      cand_avg_response_time_h: 5.0,
      cand_photos: 2,
      cand_bio_length_words: 18,
      cand_reciprocal_like: false,
    },
    matchContext: {
      shared_interests_count: 1,
      distance_km: 18.0,
      match_age_hours: 16.0,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p8',
    name: 'Owen',
    age: 32,
    photo: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [],
    bio: 'Accountant. Enjoy cooking and binge-watching documentaries.',
    interests: ['Food & Drink', 'Books'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.58,
      cand_last_active_hours: 20.0,
      cand_avg_response_time_h: 7.0,
      cand_photos: 2,
      cand_bio_length_words: 22,
      cand_reciprocal_like: false,
    },
    matchContext: {
      shared_interests_count: 1,
      distance_km: 22.0,
      match_age_hours: 24.0,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p9',
    name: 'Noah',
    age: 35,
    photo: 'https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [],
    bio: 'Engineer. I like sports.',
    interests: ['Sports'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.45,
      cand_last_active_hours: 36.0,
      cand_avg_response_time_h: 12.0,
      cand_photos: 1,
      cand_bio_length_words: 7,
      cand_reciprocal_like: false,
    },
    matchContext: {
      shared_interests_count: 0,
      distance_km: 38.0,
      match_age_hours: 48.0,
      time_of_day_evening: false,
    },
  },
  {
    id: 'p10',
    name: 'Jake',
    age: 34,
    photo: 'https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg?auto=compress&cs=tinysrgb&w=600',
    additionalPhotos: [],
    bio: 'Living my best life.',
    interests: ['Travel'],
    initiator: DEFAULT_INITIATOR,
    candidate: {
      cand_profile_completeness: 0.40,
      cand_last_active_hours: 52.0,
      cand_avg_response_time_h: 18.0,
      cand_photos: 1,
      cand_bio_length_words: 5,
      cand_reciprocal_like: false,
    },
    matchContext: {
      shared_interests_count: 0,
      distance_km: 55.0,
      match_age_hours: 72.0,
      time_of_day_evening: false,
    },
  },
];
